project:
  type: website
  output-dir: _site

website:
  title: "Vitor Lecio" # Nome que aparece na barra de navegação
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux        # 'lux', 'quartz' ou 'vapor' oferecem visuais bem distintos
    code-fold: true
    toc: false        # Remove a barra da direita (Table of Contents)
    number-sections: false

listing:
  contents: posts
  sort: "date desc"
  type: grid          # Muda de lista simples para cartões (cards)
  categories: false   # Garante que as categorias não apareçam na direita
  sort-ui: false
  filter-ui: false

execute:
  freeze: auto

